/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq.tables.records;


import com.xxx.web.jooq.tables.TOrderItem;
import com.xxx.web.jooq.tables.interfaces.ITOrderItem;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * 订单商品表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderItemRecord extends UpdatableRecordImpl<TOrderItemRecord> implements VertxPojo, Record4<Long, Long, String, LocalDateTime>, ITOrderItem {

    private static final long serialVersionUID = 208338152;

    /**
     * Setter for <code>demo.t_order_item.id</code>. 主键
     */
    @Override
    public TOrderItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>demo.t_order_item.id</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>demo.t_order_item.order_id</code>. 订单ID
     */
    @Override
    public TOrderItemRecord setOrderId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>demo.t_order_item.order_id</code>. 订单ID
     */
    @Override
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>demo.t_order_item.name</code>. 名称
     */
    @Override
    public TOrderItemRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>demo.t_order_item.name</code>. 名称
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>demo.t_order_item.order_create_time</code>. 订单创建时间
     */
    @Override
    public TOrderItemRecord setOrderCreateTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>demo.t_order_item.order_create_time</code>. 订单创建时间
     */
    @Override
    public LocalDateTime getOrderCreateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TOrderItem.T_ORDER_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return TOrderItem.T_ORDER_ITEM.ORDER_ID;
    }

    @Override
    public Field<String> field3() {
        return TOrderItem.T_ORDER_ITEM.NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TOrderItem.T_ORDER_ITEM.ORDER_CREATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrderId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDateTime component4() {
        return getOrderCreateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrderId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDateTime value4() {
        return getOrderCreateTime();
    }

    @Override
    public TOrderItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TOrderItemRecord value2(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public TOrderItemRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TOrderItemRecord value4(LocalDateTime value) {
        setOrderCreateTime(value);
        return this;
    }

    @Override
    public TOrderItemRecord values(Long value1, Long value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITOrderItem from) {
        setId(from.getId());
        setOrderId(from.getOrderId());
        setName(from.getName());
        setOrderCreateTime(from.getOrderCreateTime());
    }

    @Override
    public <E extends ITOrderItem> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOrderItemRecord
     */
    public TOrderItemRecord() {
        super(TOrderItem.T_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised TOrderItemRecord
     */
    public TOrderItemRecord(Long id, Long orderId, String name, LocalDateTime orderCreateTime) {
        super(TOrderItem.T_ORDER_ITEM);

        set(0, id);
        set(1, orderId);
        set(2, name);
        set(3, orderCreateTime);
    }

    public TOrderItemRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
