/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq.tables.pojos;


import com.xxx.web.jooq.tables.interfaces.ITOrder;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrder implements VertxPojo, ITOrder {

    private static final long serialVersionUID = -2102022802;

    private Long          id;
    private String        name;
    private LocalDateTime createTime;
    private String        userName;

    public TOrder() {}

    public TOrder(ITOrder value) {
        this.id = value.getId();
        this.name = value.getName();
        this.createTime = value.getCreateTime();
        this.userName = value.getUserName();
    }

    public TOrder(
        Long          id,
        String        name,
        LocalDateTime createTime,
        String        userName
    ) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
        this.userName = userName;
    }

    public TOrder(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TOrder setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TOrder setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public TOrder setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String getUserName() {
        return this.userName;
    }

    @Override
    public TOrder setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOrder (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(userName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITOrder from) {
        setId(from.getId());
        setName(from.getName());
        setCreateTime(from.getCreateTime());
        setUserName(from.getUserName());
    }

    @Override
    public <E extends ITOrder> E into(E into) {
        into.from(this);
        return into;
    }
}
