/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq.tables.pojos;


import com.xxx.web.jooq.tables.interfaces.ITOrderItem;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

/**
 * 订单商品表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderItem implements VertxPojo, ITOrderItem {

    private static final long serialVersionUID = -551216193;

    private Long          id;
    private Long          orderId;
    private String        name;
    private LocalDateTime orderCreateTime;

    public TOrderItem() {}

    public TOrderItem(ITOrderItem value) {
        this.id = value.getId();
        this.orderId = value.getOrderId();
        this.name = value.getName();
        this.orderCreateTime = value.getOrderCreateTime();
    }

    public TOrderItem(
        Long          id,
        Long          orderId,
        String        name,
        LocalDateTime orderCreateTime
    ) {
        this.id = id;
        this.orderId = orderId;
        this.name = name;
        this.orderCreateTime = orderCreateTime;
    }

    public TOrderItem(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TOrderItem setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getOrderId() {
        return this.orderId;
    }

    @Override
    public TOrderItem setOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TOrderItem setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public LocalDateTime getOrderCreateTime() {
        return this.orderCreateTime;
    }

    @Override
    public TOrderItem setOrderCreateTime(LocalDateTime orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOrderItem (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(name);
        sb.append(", ").append(orderCreateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITOrderItem from) {
        setId(from.getId());
        setOrderId(from.getOrderId());
        setName(from.getName());
        setOrderCreateTime(from.getOrderCreateTime());
    }

    @Override
    public <E extends ITOrderItem> E into(E into) {
        into.from(this);
        return into;
    }
}
