/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq;


import com.xxx.web.jooq.tables.TOrder;
import com.xxx.web.jooq.tables.TOrderItem;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>demo</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_ORDER_ITEM_ORDER_ID_INDEX = Indexes0.T_ORDER_ITEM_ORDER_ID_INDEX;
    public static final Index T_ORDER_USER_NAME_INDEX = Indexes0.T_ORDER_USER_NAME_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_ORDER_ITEM_ORDER_ID_INDEX = Internal.createIndex("order_id_index", TOrderItem.T_ORDER_ITEM, new OrderField[] { TOrderItem.T_ORDER_ITEM.ORDER_ID }, false);
        public static Index T_ORDER_USER_NAME_INDEX = Internal.createIndex("user_name_index", TOrder.T_ORDER, new OrderField[] { TOrder.T_ORDER.USER_NAME }, false);
    }
}
