/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq;


import com.xxx.web.jooq.tables.TOrder;
import com.xxx.web.jooq.tables.TOrderItem;
import com.xxx.web.jooq.tables.records.TOrderItemRecord;
import com.xxx.web.jooq.tables.records.TOrderRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>demo</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TOrderRecord> KEY_T_ORDER_PRIMARY = UniqueKeys0.KEY_T_ORDER_PRIMARY;
    public static final UniqueKey<TOrderItemRecord> KEY_T_ORDER_ITEM_PRIMARY = UniqueKeys0.KEY_T_ORDER_ITEM_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TOrderRecord> KEY_T_ORDER_PRIMARY = Internal.createUniqueKey(TOrder.T_ORDER, "KEY_t_order_PRIMARY", new TableField[] { TOrder.T_ORDER.ID }, true);
        public static final UniqueKey<TOrderItemRecord> KEY_T_ORDER_ITEM_PRIMARY = Internal.createUniqueKey(TOrderItem.T_ORDER_ITEM, "KEY_t_order_item_PRIMARY", new TableField[] { TOrderItem.T_ORDER_ITEM.ID }, true);
    }
}
