/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq;


import com.xxx.web.jooq.tables.TOrder;
import com.xxx.web.jooq.tables.TOrderItem;


/**
 * Convenience access to all tables in demo
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo.t_order</code>.
     */
    public static final TOrder T_ORDER = TOrder.T_ORDER;

    /**
     * 订单商品表
     */
    public static final TOrderItem T_ORDER_ITEM = TOrderItem.T_ORDER_ITEM;
}
