/*
 * This file is generated by jOOQ.
 */
package com.xxx.web.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;

import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.setOrThrow;

/**
 * 订单商品表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITOrderItem extends VertxPojo, Serializable {

    /**
     * Setter for <code>demo.t_order_item.id</code>. 主键
     */
    public ITOrderItem setId(Long value);

    /**
     * Getter for <code>demo.t_order_item.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>demo.t_order_item.order_id</code>. 订单ID
     */
    public ITOrderItem setOrderId(Long value);

    /**
     * Getter for <code>demo.t_order_item.order_id</code>. 订单ID
     */
    public Long getOrderId();

    /**
     * Setter for <code>demo.t_order_item.name</code>. 名称
     */
    public ITOrderItem setName(String value);

    /**
     * Getter for <code>demo.t_order_item.name</code>. 名称
     */
    public String getName();

    /**
     * Setter for <code>demo.t_order_item.order_create_time</code>. 订单创建时间
     */
    public ITOrderItem setOrderCreateTime(LocalDateTime value);

    /**
     * Getter for <code>demo.t_order_item.order_create_time</code>. 订单创建时间
     */
    public LocalDateTime getOrderCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITOrderItem
     */
    public void from(ITOrderItem from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITOrderItem
     */
    public <E extends ITOrderItem> E into(E into);

    @Override
    public default ITOrderItem fromJson(io.vertx.core.json.JsonObject json) {
        setOrThrow(this::setId,json::getLong,"id","java.lang.Long");
        setOrThrow(this::setOrderId,json::getLong,"order_id","java.lang.Long");
        setOrThrow(this::setName,json::getString,"name","java.lang.String");
        setOrThrow(this::setOrderCreateTime,key -> {String s = json.getString(key); return s==null?null: LocalDateTime.parse(s);},"order_create_time","java.time.LocalDateTime");
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("order_id",getOrderId());
        json.put("name",getName());
        json.put("order_create_time",getOrderCreateTime()==null?null:getOrderCreateTime().toString());
        return json;
    }

}
